version: '3'
services:
  db:
    restart: always
    image: postgres
    container_name: postgres_database
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/