# Generated by Django 5.0.1 on 2024-01-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevent',
            name='user_who_edited',
            field=models.CharField(blank=True, choices=[]),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='assigned_user',
            field=models.CharField(blank=True, choices=[]),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_user',
            field=models.CharField(blank=True, choices=[]),
        ),
    ]
