# Generated by Django 5.0.1 on 2024-01-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_historicalevent_user_who_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalevent',
            name='user_who_edited',
            field=models.CharField(blank=True, choices=[('PanBezrobotny', 'PanBezrobotny'), ('matir', 'matir')]),
        ),
    ]
