# Generated by Django 5.0.1 on 2024-01-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_historicalevent_user_who_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='author',
            field=models.CharField(default='Administrator', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(default='Administrator', max_length=100),
        ),
    ]
