# Generated by Django 5.0.1 on 2024-01-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_alter_task_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='id',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
