# Generated by Django 5.0.1 on 2024-01-30 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_historicalevent_task_alter_task_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalevent',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.task'),
        ),
    ]
