# Generated by Django 5.0.1 on 2024-01-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_alter_historicalevent_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalevent',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task'),
        ),
    ]
