# Generated by Django 5.0.1 on 2024-01-30 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0012_alter_task_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevent',
            name='occurrence_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
