# Generated by Django 5.0.1 on 2024-01-30 20:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0013_historicalevent_occurrence_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_who_edited', models.CharField(blank=True, choices=[('PanBezrobotny', 'PanBezrobotny'), ('matir', 'matir')])),
                ('field_to_update', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('occurrence_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalEvent',
        ),
    ]
