# Generated by Django 5.0.1 on 2024-01-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0015_alter_historicaltaskevent_field_to_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltaskevent',
            name='task',
        ),
        migrations.AddField(
            model_name='historicaltaskevent',
            name='action_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
