# Generated by Django 5.0.1 on 2024-01-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0016_remove_historicaltaskevent_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaskevent',
            name='action_name',
            field=models.CharField(max_length=20),
        ),
    ]
