# Generated by Django 5.0.1 on 2024-01-31 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0018_remove_historicaltaskevent_action_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaskevent',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task'),
        ),
    ]
