# Generated by Django 5.0.1 on 2024-01-31 11:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0019_alter_historicaltaskevent_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaskevent',
            name='field_to_update',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicaltaskevent',
            name='new_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicaltaskevent',
            name='old_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
    ]
