# Generated by Django 5.0.1 on 2024-01-31 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0020_alter_historicaltaskevent_field_to_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaskevent',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.task'),
        ),
    ]
