# Generated by Django 5.0.1 on 2024-01-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0021_alter_historicaltaskevent_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('Nowy', 'Nowy'), ('W toku', 'W toku'), ('Rozwiązany', 'Rozwiązany')], default='CREATED'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Nowy', 'Nowy'), ('W toku', 'W toku'), ('Rozwiązany', 'Rozwiązany')], default='CREATED'),
        ),
    ]
