# Generated by Django 5.0.1 on 2024-01-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0022_alter_historicaltask_status_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltaskevent',
            old_name='field_to_update',
            new_name='fields_to_update',
        ),
        migrations.RenameField(
            model_name='historicaltaskevent',
            old_name='new_value',
            new_name='new_values',
        ),
        migrations.RenameField(
            model_name='historicaltaskevent',
            old_name='old_value',
            new_name='old_values',
        ),
        migrations.RemoveField(
            model_name='historicaltaskevent',
            name='task',
        ),
        migrations.AddField(
            model_name='historicaltaskevent',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaltaskevent',
            name='task_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
