# Generated by Django 5.0.1 on 2024-01-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0023_rename_field_to_update_historicaltaskevent_fields_to_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaskevent',
            name='task_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaltaskevent',
            name='task_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
