# Generated by Django 5.0.1 on 2024-01-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0024_alter_historicaltaskevent_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaskevent',
            name='assigned_user',
            field=models.CharField(default='fake', max_length=100),
            preserve_default=False,
        ),
    ]
