# Generated by Django 5.0.1 on 2024-01-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0025_historicaltaskevent_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaskevent',
            name='action',
            field=models.CharField(default='Update', max_length=100),
            preserve_default=False,
        ),
    ]
