# Generated by Django 5.0.1 on 2024-02-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0026_historicaltaskevent_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_string', models.CharField(max_length=100)),
            ],
        ),
    ]
