# Generated by Django 5.0.1 on 2024-02-02 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0027_taskfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_manager.task')),
            ],
        ),
    ]
