name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker stack
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: task_manager
    - name: Stop stack
      if: always()
      run: docker-compose -f "docker-compose.yml" down
