name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker stack
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Stop stack
      if: always()
      run: docker-compose -f "docker-compose.yml" down
    - name: Save docker stack
      run: |
        services=$(docker-compose config --services)
        app_name = docker images --format "{{.Repository}}" | head -n 1
        docker save -o "${app_name}.tar" "${app_name}"
    - name: Move Docker image tar files to repository directory
      run: |
        mkdir -p /artifacts
        mv *.tar /artifacts
