name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the docker stack
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Save the docker stack
      run: docker save -o "matrus98-mga_task_repo_my_web_app.tar" "matrus98-mga_task_repo_my_web_app"
    - name: Stop stack
      if: always()
      run: docker-compose -f "docker-compose.yml" down
    - name: Upload docker stack
      uses: actions/upload-artifact@v3
      with:
        name: task_manager
        path: matrus98-mga_task_repo_my_web_app.tar
